# Generated by Django 4.0.5 on 2022-06-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Writer', '0002_alter_customuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
