# Generated by Django 4.0.5 on 2022-06-22 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
        ('Bloglar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=100)),
                ('slider_description', models.TextField()),
                ('slider_image', models.ImageField(upload_to='slider')),
                ('slider_status', models.BooleanField(default=True)),
                ('create_slider_date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_category', to='Category.category')),
            ],
        ),
    ]
