# Generated by Django 4.0.5 on 2022-06-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloglar', '0002_sliderblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='topPicksOfMonth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='trendingBlog',
            field=models.BooleanField(default=False),
        ),
    ]
