# Generated by Django 4.0.5 on 2022-06-25 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bloglar', '0004_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment_writer', to=settings.AUTH_USER_MODEL),
        ),
    ]
