# Generated by Django 4.0.5 on 2022-06-26 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bloglar', '0005_blogcomment_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment_writer', to=settings.AUTH_USER_MODEL),
        ),
    ]
