# Generated by Django 4.0.5 on 2022-06-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloglar', '0006_alter_blogcomment_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_blog_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='created_commnet_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sliderblog',
            name='create_slider_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
