# Generated by Django 4.0.5 on 2022-06-26 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=50)),
                ('message', models.CharField(max_length=200)),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to=settings.AUTH_USER_MODEL)),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('message_date',),
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=50)),
                ('receiver_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver1', to=settings.AUTH_USER_MODEL)),
                ('sender_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
