# Generated by Django 4.0.5 on 2022-06-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
